spring.application.name=telegram-bot
bot.name=animal_shelterismy1bot
bot.token=7821484838:AAEHTSQEvnjuEIqLip2AZx2CTvbtOQ-yQ1A
spring.datasource.url=jdbc:postgresql://localhost:5432/pet_shelter
spring.datasource.username=postgres
spring.datasource.password=damir_999
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
